version: "3.8"

services:
  onthespot:
    build: .
    container_name: onthespot-web
    ports:
      - "5500:5500"
    volumes:
      - /home/aiden/Jellyfin/Music/Tracks:/app/downloads
    restart: unless-stopped
